import type { Metadata } from "next";
import {Inter } from 'next/font/google'
import "./globals.css";
import Header from "@/components/Header";
import {ClerkProvider, SignedIn, SignedOut, SignInButton, UserButton} from '@clerk/nextjs'
const inter = Inter({subsets:["latin"]})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${inter.className}`}
      >
        <header>
          <Header/>
        </header>

       <main>

    

{children}
</main>    
        <footer  className="fixed-bottom-0 bg-blue-50 py-12">
          <div className="container mx-auto px-4 text-center text-gray-600 ">
            <p>Made by firdaus naseem</p>
          </div>
        </footer>
      
      </body>
    </html>
    </ClerkProvider>
  );
}
